### ISSUE TITLE
Fall damage returns

### ISSUE THREAD

**Issue by byKrem** [Kriper1111/R2-FixChefFoodSuck#2] opened 2024-09-03 05:13 UTC
I like Acrid's shift because with its use there is no fall damage. But by setting this mod, fall damage appeared after using the skill. It makes hard to use it on Eclipse 3 or above. Can you fix it so it works like before the DLC release?
![image](https://github.com/user-attachments/assets/0563e1b3-35f4-4d6a-b58a-e90571c93dfb)

**Comment by Kriper1111** [comment] 2024-09-03 05:51
Thanks for the heads up, I should've done a better job testing it. I will look into it.

**Comment by Kriper1111** [comment] 2024-09-03 05:54
Did your jump land out of the map or on the ground jumping off of a cliff?

**Comment by byKrem** [comment] 2024-09-03 06:53
I just stood there, jumped up and landed where I was standing.

**Comment by Kriper1111** [comment] 2024-09-03 08:55
I see, thanks. Got to reproduce it, but I have only vague ideas of what to do about it.

A possible band-aid solution would be to do a weird mix of features - let Acrid's Leap collide with entities, but slide off of trees and cliffs.

It's a weird event race, game deals fall damage the same frame as it clears Acrid's fall damage immunity flag, due to him hitting the ground on the frame before, possibly because the fall damage is calculated on the server, or through server's command, while regular movement hit isn't.

**Comment by Kriper1111** [comment] 2024-09-03 15:10
Okay, I have uploaded a [pre-release](https://github.com/Kriper1111/R2-FixChefFoodSuck/releases/tag/v1.3.0-rc2) containing that fix, it would be nice if you could test it out. I'm not entirely sure if it would work in multiplayer, especially over slower networks. Multiplayer needs testing.

_Technical info following._
That theory was kinda wrong - but just adding one frame delay before the leap explosion occurs seems to be sufficient. Technically it's not a data race, the character control system they're using sometimes dispatches the GroundHit event (which deals fall damage) a frame after it dispatches the event that tells we have landed on the ground (but not hit it yet, and which is inevitably clears the fall damage immunity flag). So one FixedUpdate frame delay should be sufficient. Although janky.

I kinda understand why Gearbox just kinda.. shoved it. I still disapprove but I understand then just a bit better.

**Comment by DamageMaximo** [comment] 2024-09-03 17:59
I am still experiencing fall damage when falling using the utility

**Comment by Kriper1111** [comment] 2024-09-03 18:44
@DamageMaximo Did you try the pre-release build linked above or 1.1.0 from Thunderstore? Were you playing solo or multiplayer? If you were in multiplayer, were you host or guest?

I do suggest trying the pre-release if you haven't already.

And by linked above I actually mean linked below (but I will edit the previous comment as well)
https://github.com/Kriper1111/R2-FixChefFoodSuck/releases/tag/v1.3.0-rc2

**Comment by DamageMaximo** [comment] 2024-09-04 23:40
it's fixed now as far as I could tell

**Comment by Kriper1111** [comment] 2024-09-05 00:17
Yippie. For my own tests and theories, it should work solo and for hosts.

As for the guests.. It will need a netcode patch of some degree. I think I'll create another issue for the multiplayer side and close this one.

**Closed as completed** 2024-09-05 00:17 UTC
Labels: single-player, multiplayer-as-host
